// ============================================================================
// Agent System Type Definitions
// ============================================================================

/**
 * Roles that agents can fulfill in the orchestration system.
 */
export enum AgentRole {
  MANAGER = 'MANAGER',
  ARCHITECT = 'ARCHITECT',
  FRONTEND = 'FRONTEND',
  BACKEND = 'BACKEND',
  DATABASE = 'DATABASE',
  UI_UX = 'UI_UX',
  SECURITY = 'SECURITY',
  TESTING = 'TESTING',
  DOCUMENTATION = 'DOCUMENTATION',
  DEVOPS = 'DEVOPS',
  API = 'API',
  PERFORMANCE = 'PERFORMANCE',
  CODE_REVIEW = 'CODE_REVIEW',
  ACCESSIBILITY = 'ACCESSIBILITY',
}

/**
 * Lifecycle states for an agent.
 */
export enum AgentState {
  IDLE = 'IDLE',
  WORKING = 'WORKING',
  WAITING = 'WAITING',
  BLOCKED = 'BLOCKED',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}

/**
 * Priority levels for tasks.
 */
export enum TaskPriority {
  CRITICAL = 0,
  HIGH = 1,
  MEDIUM = 2,
  LOW = 3,
}

/**
 * Status of a task in the execution pipeline.
 */
export enum TaskStatus {
  PENDING = 'PENDING',
  QUEUED = 'QUEUED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
  BLOCKED = 'BLOCKED',
}

/**
 * Message types for inter-agent communication.
 */
export enum MessageType {
  TASK_ASSIGNMENT = 'TASK_ASSIGNMENT',
  TASK_RESULT = 'TASK_RESULT',
  CONFLICT_DETECTED = 'CONFLICT_DETECTED',
  RESOLUTION_REQUEST = 'RESOLUTION_REQUEST',
  STATUS_UPDATE = 'STATUS_UPDATE',
  CONTEXT_SHARE = 'CONTEXT_SHARE',
  REQUEST = 'REQUEST',
  REPLY = 'REPLY',
}

/**
 * Describes a capability an agent possesses.
 */
export interface AgentCapability {
  name: string;
  description: string;
  inputSchema?: Record<string, unknown>;
  outputSchema?: Record<string, unknown>;
}

/**
 * Represents a task in the orchestration system.
 */
export interface AgentTask {
  id: string;
  type: string;
  description: string;
  input: Record<string, unknown>;
  output?: Record<string, unknown>;
  status: TaskStatus;
  dependencies: string[];
  assignedAgent?: string;
  priority: TaskPriority;
  parentTaskId?: string;
  createdAt: Date;
  startedAt?: Date;
  completedAt?: Date;
  error?: string;
  retryCount: number;
  maxRetries: number;
}

/**
 * Message exchanged between agents.
 */
export interface AgentMessage {
  id: string;
  from: string;
  to: string;
  type: MessageType;
  payload: Record<string, unknown>;
  timestamp: Date;
  correlationId: string;
}

/**
 * Configuration for the orchestrator.
 */
export interface OrchestratorConfig {
  maxConcurrentTasks: number;
  taskTimeout: number;
  retryAttempts: number;
  circuitBreakerThreshold: number;
  circuitBreakerResetTime: number;
}

/**
 * Execution plan produced by the TaskDecomposer.
 */
export interface ExecutionPlan {
  id: string;
  description: string;
  tasks: AgentTask[];
  estimatedComplexity: number;
  parallelizableGroups: string[][];
}

/**
 * Represents a conflict between agent outputs.
 */
export interface ConflictInfo {
  id: string;
  agentIds: string[];
  taskIds: string[];
  description: string;
  conflictingOutputs: Record<string, unknown>[];
  resolvedOutput?: Record<string, unknown>;
  resolved: boolean;
}

/**
 * Memory entry stored by an agent.
 */
export interface MemoryEntry {
  id: string;
  agentId: string;
  type: 'short_term' | 'long_term' | 'shared';
  content: string;
  metadata: Record<string, unknown>;
  timestamp: Date;
  relevanceScore?: number;
}

/**
 * Token budget allocation for an agent.
 */
export interface TokenBudget {
  agentId: string;
  totalBudget: number;
  used: number;
  reserved: number;
  available: number;
}

// ============================================================================
// Worker Pool & Load Balancer Types
// ============================================================================

/**
 * Load balancing strategies for distributing tasks to workers.
 */
export enum LoadBalancerStrategy {
  ROUND_ROBIN = 'ROUND_ROBIN',
  LEAST_LOADED = 'LEAST_LOADED',
  CAPABILITY_MATCH = 'CAPABILITY_MATCH',
}

/**
 * Configuration for the WorkerPool.
 */
export interface WorkerPoolConfig {
  minWorkers: number;
  maxWorkers: number;
  scaleUpThreshold: number;
  scaleDownThreshold: number;
  strategy: LoadBalancerStrategy;
}

/**
 * Statistics about the current state of a worker pool.
 */
export interface PoolStats {
  totalWorkers: number;
  activeWorkers: number;
  idleWorkers: number;
  queuedTasks: number;
  avgTaskDuration: number;
}

// ============================================================================
// Agent Output Types
// ============================================================================

/**
 * A file generated by an agent during task execution.
 */
export interface GeneratedFile {
  path: string;
  content: string;
  language: string;
  action: 'create' | 'update' | 'delete';
}

/**
 * Structured output produced by an agent.
 */
export interface AgentOutput {
  type: string;
  content: string;
  structured: Record<string, unknown>;
  files?: GeneratedFile[];
  confidence: number;
}

// ============================================================================
// Agent Protocol Types
// ============================================================================

/**
 * Protocol message types for structured inter-agent communication.
 */
export enum ProtocolMessageType {
  REVIEW_REQUEST = 'REVIEW_REQUEST',
  CONTEXT_PROVISION = 'CONTEXT_PROVISION',
  CLARIFICATION_REQUEST = 'CLARIFICATION_REQUEST',
  SUBTASK_DELEGATION = 'SUBTASK_DELEGATION',
}
